version: "3.8"

services:
    myflask:
        build: .
        ports:
            - "5000:5000"
        environment:
            - FLASK_ENV=development
        volumes:
            - ./database:/usr/src/app/database
